apiVersion: v1
kind: Secret
metadata:
  name: finapp-env
type: Opaque
stringData:
  ROOT_PATH: "C:\\Prasath\\FinProj\\Datasets\\SCRIP"
  MANIFEST_PATH: "C:\\Prasath\\FinProj\\Datasets\\manifest.csv"


